
server:
  port: 8080
  assetsPath: 'assets'
  cookies:
    secure: true # clients will transmit cookies only over TLS secured connections
    httpOnly: true # clients will not grant javascript pages access to the cookies in general
    path: "/" # clients will transmit cookies to this path and all its sub paths

csrf:
  totpTtlSeconds: 300 # 5 minutes
  totpKey: null # a random key is generated upon startup
  hmacKey: null # a random key is generated upon startup

hydra:
  adminUrl: http://localhost:4445
  timeoutMilliseconds: 5000
  rememberForSeconds: 604800 # 7 days

ldap:
  serverUrl: ldaps://localhost:636
  bindDn: cn=binduser,ou=Users,dc=lbarnkow,dc=github,dc=com
  bindPassword: weakpassword
  userSearchBaseDn: ou=Users,dc=lbarnkow,dc=github,dc=com
  userSearchObjectClass: person
  userAttributeUid: uid
  userAttributeGivenName: givenName
  userAttributeSurname: sn
  userAttributeMail: mail
