volumes:
  openldap_data:
    driver: local

networks:
  minchirnet:
    name: minchir

services:
  glauth:
    container_name: glauth.minchir
    image: docker.io/glauth/glauth:v2.1.0
    ports:
      - 10389:10389
      - 10636:10636
    networks:
      - minchirnet
    volumes:
      - type: bind
        source: ./certs/
        target: /certs/
        bind:
          selinux: z
      - type: bind
        source: ./glauth/config.cfg
        target: /app/config/config.cfg
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M

  openldap:
    container_name: openldap.minchir
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '20389:20389'
    networks:
      - minchirnet
    environment:
      - LDAP_PORT_NUMBER=20389
      - LDAP_ROOT=dc=minchir,dc=lbarnkow
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ALLOW_ANON_BINDING=no
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - type: bind
        source: ./certs/
        target: /certs/
        bind:
          selinux: z
      - type: bind
        source: ./openldap/init.ldif
        target: /ldifs/init.ldif
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M

  hydra:
    container_name: hydra.minchir
    image: docker.io/oryd/hydra:v1.11.10
    command: serve all --config /hydra.yaml
    ports:
      - '14444:14444'
      - '14445:14445'
    networks:
      - minchirnet
    volumes:
      - type: bind
        source: ./certs/
        target: /certs/
        bind:
          selinux: z
      - type: bind
        source: ./hydra/hydra.yaml
        target: /hydra.yaml
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M
    healthcheck:
      test: [ "CMD", "hydra", "clients", "list", "--skip-tls-verify", "--endpoint", "https://localhost:14445/" ]
      interval: 10s
      start_period: 60s

  hydra-client-bootstrap:
    depends_on:
      hydra:
        condition: service_healthy
    container_name: hydra-client-bootstrap.minchir
    image: docker.io/oryd/hydra:v1.11.10
    entrypoint: /bootstrap.sh
    networks:
      - minchirnet
    volumes:
      - type: bind
        source: ./hydra/bootstrap.sh
        target: /bootstrap.sh
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M

  dummyapp:
    container_name: dummyapp.minchir
    image: docker.io/library/nginx:alpine
    networks:
      - minchirnet
    volumes:
      - type: bind
        source: ./dummyapp/
        target: /usr/share/nginx/html/
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M
    ports:
      - 28080:80
