name: ci

on:
  push

jobs:
  # gradle build & test
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          java -version
          cd app
          ../gradlew --no-daemon test installDist distZip

      - if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: gradle-install
          path: app/build/install/app/

      - if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: native-image-configs
          path: app/native-image

      - if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: gradle-dist
          path: app/build/distributions/app.zip

  # build native-image for linux/amd64
  native-image-linux-amd64:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: java
    runs-on: ubuntu-latest
    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          java -version
          cd app
          ../gradlew --no-daemon test installDist distZip

      - run: |
          cd native-image-configs
          $GRAALVM_HOME/bin/../lib/svm/bin/native-image \
              --allow-incomplete-classpath \
              --no-fallback \
              --static \
              --libc=glibc \
              --class-path './config-classpath/:../gradle-install/lib/*' \
              com.github.lbarnkow.minchir.App \
              minchir-linux-amd64

      - uses: actions/upload-artifact@v3
        with:
          name: native-image-linux-amd64
          path: native-image-configs/minchir-linux-amd64

  # build native-image for linux/arm64
  native-image-linux-arm64:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    needs: java
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: gradle-install
          path: gradle-install

      - uses: actions/download-artifact@v3
        with:
          name: native-image-configs
          path: native-image-configs

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/arm64
          load: true
          push: false
          tags: lbarnkow/minchir-temp:${{ github.sha }}

      - run: |
          mkdir output
          CONTAINER=$(docker container create lbarnkow/minchir-temp:$GITHUB_SHA sh)
          docker container cp $CONTAINER:/minchir-linux-arm64 output/
          docker container rm $CONTAINER
          file output/minchir-linux-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: native-image-linux-arm64
          path: output/minchir-linux-arm64

  # publish release
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [native-image-linux-amd64, native-image-linux-arm64]
    runs-on: ubuntu-latest
    steps:
      - run: uname --all # TODO
